# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    git config --global user.email "sugesh.s@hotmail.com"
    git config --global user.name "sugeshsuseelan"
    git add .
    git commit -m "Commited from Production-temp branch"
    git remote rm origin
    git remote add origin https://github.com/sugeshsuseelan/Demo.git
    git push https://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@github.com/github.com/sugeshsuseelan/Demo.git HEAD:Prod-temp
    
  displayName: 'Push to Repo'
